# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='enterprise_ORDER',
            fields=[
                ('OrderName', models.CharField(max_length=50)),
                ('OrderID', models.IntegerField(primary_key=True, serialize=False)),
                ('ADDRESS', models.CharField(default=0, max_length=100)),
                ('DATE', models.DateField(null=True)),
                ('DES', models.TextField(null=True)),
                ('Price1', models.IntegerField()),
                ('Telephone', models.IntegerField()),
                ('Status', models.IntegerField()),
                ('GooDID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.GOOD')),
                ('UserName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
