# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-22 20:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_enterprise_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise_order',
            name='UserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
