# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20170527_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='alipayID',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
