# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_pay_alipayid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise_order',
            name='OrderID',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
