# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20170603_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise_order',
            name='OrderID',
            field=models.IntegerField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enterprise_order',
            name='Telephone',
            field=models.IntegerField(max_length=100),
        ),
    ]
