# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-03 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20170603_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='GoodPrice',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='good',
            name='GoodPrice1',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='good',
            name='GoodPrice2',
            field=models.FloatField(),
        ),
    ]
